server:
  port: 9101

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://10.1.31.23:9901/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_user
    username: user_service
    password: Us135792468
    driver-class-name: com.mysql.jdbc.Driver
  jpa.properties.hibernate.hbm2ddl.auto: update