server:
  port: 9999

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://10.1.31.23:9901/eureka/
      
zuul:
  routes:
    user-api:
      path: /user/**
      serviceId: user_service