server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_cont
    username: cont_service
    password: Co135792468
    driver-class-name: com.mysql.jdbc.Driver
  jpa.properties.hibernate.hbm2ddl.auto: update